// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteRecurringSeries(arg1) {
  return window['go']['main']['App']['DeleteRecurringSeries'](arg1);
}

export function ExportICS() {
  return window['go']['main']['App']['ExportICS']();
}

export function GetAllEvents() {
  return window['go']['main']['App']['GetAllEvents']();
}

export function ImportICS() {
  return window['go']['main']['App']['ImportICS']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveEvent(arg1) {
  return window['go']['main']['App']['SaveEvent'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UpdateEvent(arg1, arg2) {
  return window['go']['main']['App']['UpdateEvent'](arg1, arg2);
}
