// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function DeleteEvent(arg1:number):Promise<void>;

export function DeleteRecurringSeries(arg1:number):Promise<void>;

export function ExportICS():Promise<string>;

export function GetAllEvents():Promise<Array<database.Event>>;

export function ImportICS():Promise<number>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveEvent(arg1:main.EventInput):Promise<number>;

export function SelectFile():Promise<string>;

export function UpdateEvent(arg1:number,arg2:main.EventInput):Promise<void>;
